engines:
  credo:
    enabled: true
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        elixir:
        javascript:
  fixme:
    enabled: true
  csslint:
    enabled: false
