# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: strobeaudio/circleci-elixir:latest
        environment:
          MIX_TARGET: host
          MIX_ENV: test

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-v1-{{ checksum "mix.lock" }}
            - deps-v1
      - restore_cache:
          keys:
            - build-v1-{{ .Branch }}
            - build-v1

      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get

      - save_cache:
          key: deps-v1-{{ checksum "mix.lock" }}
          paths:
            - deps
            - /home/circleci/.mix
      - save_cache:
          key: deps-v1
          paths:
            - deps
            - /home/circleci/.mix

      - run: mix compile

      - save_cache:
          key: build-v1-{{ .Branch }}
          paths:
            - _build
            - /home/circleci/.cache/rebar3
      - save_cache:
          key: build-v1
          paths:
            - _build
            - /home/circleci/.cache/rebar3

      - run: mix test --trace
