# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.4.5
        environment:
          MIX_TARGET: host
          MIX_ENV: test

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force

      - restore_cache:
          keys:
            - deps-v1-{{ checksum "mix.lock" }}
            - deps-v1
            - build-v1-{{ .Branch }}
            - build-v1

      - run: mix deps.get

      - save_cache:
          key: deps-v1-{{ checksum "mix.lock" }}
          paths:
            - deps
      - save_cache:
          key: deps-v1
          paths:
            - deps

      - run: mix compile

      - save_cache:
          key: build-v1-{{ .Branch }}
          paths:
            - _build

      - save_cache:
          key: build-v1
          paths:
            - _build

      - run: mix test --trace
